In [1]:
import numpy as np

In [36]:
n = 3
N = 7
k = 2

def list_to_str(l):
    return ''.join(str(e) for e in l)

def check_guess_right(b, bad_coin_index):
    guess_index = np.array(int(list_to_str(b[::-1]), base=2) - 1)
    
    return guess_index == bad_coin_index

In [37]:
bad_coin_index = np.random.randint(N, size=(k))
sensing_matrix = np.random.randint(2, size=(n, N))

In [38]:
bad_coin_index

array([4, 5])

In [39]:
sensing_matrix

array([[1, 0, 1, 1, 0, 1, 0],
       [1, 0, 1, 1, 1, 0, 0],
       [0, 1, 0, 1, 0, 1, 1]])

In [45]:
x = np.array([1, 0, 1, 0, 0, 0, 0])

In [46]:
b = sensing_matrix.dot(x)

In [47]:
b

array([2, 2, 0])

In [48]:
np.array(int(list_to_str(b[::-1]), base=2) - 1)

ValueError: invalid literal for int() with base 2: '022'

In [43]:
check_guess_right(b, bad_coin_index)

array([False, False], dtype=bool)

In [27]:
a = np.array([1, 2, 3, 4])
np.linalg.norm(a, ord=1)

10.0