In [1]:
import numpy as np

In [36]:
n = 3
N = 7
k = 2

def list_to_str(l):
    return ''.join(str(e) for e in l)

def check_guess_right(b, bad_coin_index):
    guess_index = np.array(int(list_to_str(b[::-1]), base=2) - 1)
    
    return guess_index == bad_coin_index

In [37]:
bad_coin_index = np.random.randint(N, size=(k))
sensing_matrix = np.random.randint(2, size=(n, N))

In [38]:
bad_coin_index

array([4, 5])

In [39]:
sensing_matrix

array([[1, 0, 1, 1, 0, 1, 0],
       [1, 0, 1, 1, 1, 0, 0],
       [0, 1, 0, 1, 0, 1, 1]])

In [45]:
x = np.array([1, 0, 1, 0, 0, 0, 0])

In [46]:
b = sensing_matrix.dot(x)

In [47]:
b

array([2, 2, 0])

In [48]:
np.array(int(list_to_str(b[::-1]), base=2) - 1)

ValueError: invalid literal for int() with base 2: '022'

In [43]:
check_guess_right(b, bad_coin_index)

array([False, False], dtype=bool)

In [27]:
a = np.array([1, 2, 3, 4])
np.linalg.norm(a, ord=1)

10.0

步驟
0. 初始化
1. 造出隨機x vector與$\Phi$
2. 用$\Phi$x得到b
3. 現在假定已知$\Phi$和b，用線性規劃解x，在$\Phi$x = b的限制下，最小化$\Vert{x}\Vert_{1}$
4. 比對找出的x跟原本的x是否相同
5. 重複0-4步驟1000次算出猜對的機率

In [28]:
# 步驟一
N = 100  #總共100個coin
n = 20   #可以測量20次
k = 3    #有幾個bad coin

In [29]:
# 步驟二
# 製造x vector
x = np.zeros(100)
x[np.random.randint(100, size=(k))] = 1
# 製造sensing_matrix
sensing_matrix = np.random.randint(2, size=(n, N))

In [30]:
# 步驟三
b = sensing_matrix.dot(x)

In [31]:
# 步驟四


array([ 2.,  3.,  2.,  1.,  2.,  3.,  2.,  1.,  2.,  0.,  0.,  2.,  1.,
        2.,  3.,  3.,  2.,  1.,  1.,  3.])

In [32]:
x

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])